#####################################################################################
#                                                                                   #
#    #          ####     ####    #    #   #          ####     ####    #   #    #    #
#    #         #    #   #    #   #   #    #         #    #   #    #   #   ##   #    #
#    #         #    #   #        ####     #         #    #   #        #   # #  #    #
#    #         #    #   #        #  #     #         #    #   #  ###   #   #  # #    #
#    #         #    #   #    #   #   #    #         #    #   #    #   #   #   ##    #
#    #######    ####     ####    #    #   #######    ####     ####    #   #    #    #
#                                                                                   #
#####################################################################################
name: LockLogin
version: ${project.version}
author: ${project.author}
description: ${project.description}
website: ${project.url}
main: ml.karmaconfigs.locklogin.plugin.bukkit.Main
database: false
api-version: 1.13
softdepend:
  - PlaceholderAPI



#####################################################################################################
#                                                                                                   #
#      ######     #######     ##     ##   ##     ##      ###      ##    ##   ########     ######    #
#    ##     ##   ##     ##    ###   ###   ###   ###     ## ##     ###   ##   ##     ##   ##    ##   #
#    ##          ##     ##    #### ####   #### ####    ##   ##    ####  ##   ##     ##   ##         #
#    ##          ##     ##    ## ### ##   ## ### ##   ##     ##   ## ## ##   ##     ##    ######    #
#    ##          ##     ##    ##     ##   ##     ##   #########   ##  ####   ##     ##         ##   #
#    ##     ##   ##     ##    ##     ##   ##     ##   ##     ##   ##   ###   ##     ##   ##    ##   #
#      ######     #######     ##     ##   ##     ##   ##     ##   ##    ##   ########     ######    #
#                                                                                                   #
#####################################################################################################
commands:
  locklogin:
    description: The command to manage the plugin, such as reload, or apply updates
  setloginspawn:
    description: The command to set login spawn, must be enabled in config.yml!
  register:
    description: The command that allows a player to register
  login:
    description: The command that allows a player to login into his account
  pin:
    description: The command that allows a player to manage his pin
  2fa:
    description: The command that allows a player to manage his 2FA settings
  playerinfo:
    description: The command that allows a player to view a player information
  alias:
    description: The command that allows a player to create/manage aliases of playerinfo
  account:
    description: The command that allows a player to manage account
  lastloc:
    description: The command that allows a player to manage last locations



#################################################################
#                                                               #
#    ########    ########   ########    ##     ##    ######     #
#    ##     ##   ##         ##     ##   ###   ###   ##    ##    #
#    ##     ##   ##         ##     ##   #### ####   ##          #
#    ########    ######     ########    ## ### ##    ######     #
#    ##          ##         ##   ##     ##     ##         ##    #
#    ##          ##         ##    ##    ##     ##   ##    ##    #
#    ##          ########   ##     ##   ##     ##    ######     #
#                                                               #
#################################################################
permissions:
  locklogin.reload:
    children:
      locklogin.reload.config:
        description: The permission required to reload only configuration file
        default: false
      locklogin.reload.messages:
        description: The permission required to reload only messages file
        default: false
    description: The permission required to reload configuration/messages files
    default: false
  locklogin.applyupdates:
    children:
      locklogin.applyupdates.unsafe:
        description: The permission required to apply unsafe updates
        default: false
    description: The permission required to apply LockLogin update
    default: false
  locklogin.migrate:
    children:
      locklogin.migrate.external:
        description: The permission required to perform/request module migrations
        default: false
      locklogin.migrate.authme:
        description: The permission required to perform/request authme migrations
        default: false
      locklogin.migrate.loginsecurity:
        description: The permission required to perform/request loginsecurity migrations
        default: false
    description: The permission required to perform/request migrations
    default: false
  locklogin.setspawn:
    description: The permission required to set the login spawn location
    default: op
  locklogin.info:
    children:
      locklogin.info.request:
        description: The permission required to request other player information
        default: false
      locklogin.info.alt:
        children:
          locklogin.info.alt.alert:
            description: The permission required to receive alerts when a player with alt account joins the server
            default: false
        description: The permission required to request alt account information
        default: false
    description: The permission required to request player or plugin information
    default: op
  locklogin.account:
    children:
      locklogin.account.close:
        description: The permission required to close a client account
        default: false
      locklogin.account.remove:
        description: The permission required to remove a client account
        default: false
      locklogin.account.unlock:
        description: The permission required to unlock a client account
        default: false
      locklogin.account.location:
        description: The permission required to manage player(s) last location
        default: false
    description: The permission required to manage a player account
    default: false
  locklogin.forcefa:
    description: The permission that will force the player run /2fa setup after register
    default: false
  locklogin.alias:
    description: The permission to create/destroy or manage aliases
    default: false